version: '3.3'
networks:
  apex:
    driver: bridge
services:
  frontend:
    container_name: apex-frontend
    image: winnkyaw/apex:latest
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - apex
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/apex
      - SECRET="mysecret"
  
  nginx:
    image: nginx:latest
    networks:
      - apex
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    networks:
      - apex
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=apex
      - TZ="+00:00"
    ports:
      - "3306:3306"

volumes:
  db:
    driver: local